---
title: "Data Wrangling Steps"
author: "James Matheson"
date: "June 22, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Data Wrangling Steps
#Goal: Create Two Data Frames, One for Train Set and One for Test Set


##For Train Set
###application_train is the primary set to join to - joined version will be called"train_merge"

##For Test Set
###application_test is the primary set to join to - joined version will be called"test_merge"


#Steps per file
##bureau has multiple rows per applicant
simplify this data separately for import into train_merge and test_merge
- 

##bureau_balance - multiple rows per SK_ID_BUREAU
can use filter(bureau_balance, sk_id_bureau == "_number to filter_on")

##credit_card_balance
up to 96 months of card balance data per applicant, in multiple rows
- check percentage of missed payments

##installments_payments
multiple rows per applicant
to view use dplyr::arrange(installments_payments, SK_ID_PREV, NUM_INSTALMENT_NUMBER)

##POS_CASH_balance
multiple rows per applicant
credit histtory on point of sale and cash balance credit